{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "basic-service.name" . }}-env
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "basic-service.name" . }}
    {{- with .Values.labels }}
    {{- include "basic-service.labels" . | nindent 4 }}
    {{- end }}
data:
{{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
