{{- if and .Values.serviceTargetPort .Values.servicePort }}
apiVersion: v1
kind: Service
metadata:
  name: {{template "basic-service.name" .}}-svc
  namespace: {{.Values.namespace}}
  labels:
    app: {{template "basic-service.name" .}}
    {{- if .Values.labels }}
    {{- include "basic-service.labels" $ | indent 4}}
    {{- end }}
spec:
  type: {{.Values.serviceType}}
  ports:
  - name: {{ if .Values.serviceMonitor.enabled }}{{ .Values.serviceMonitor.port | default "http" }}{{ else }}tcp-{{ template "basic-service.name" . }}{{ end }}
    port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    protocol: TCP
  {{- if .Values.extraPorts }}
    {{ toYaml .Values.extraPorts | nindent 2}}
  {{- end }}
  selector:
    {{- include "basic-service.selectorLabels" . | nindent 4 }}
{{- end}}
